### ISSUE TITLE
Docker doesn't save images...

### ISSUE THREAD

**Issue by fbhradec** [ShaneMcC/PXE-Manager#130]
I'm running pxe-manager in docker using the main Dockerfile from this depot, and although everything seems to be running fine, when I create a new image nothing is saved, and my image list stays empty. 

There are no error messages in logs or anything, so I'm not sure what's going wrong. 

I tried with and without mapping `/var/lib/tftpboot` and `/pxemanager/data` to a local folder, same result. 

any ideas of what's going on or how I could debug this?

**Comment by hradec** [comment]
This is the `run.sh` file I created to run it using docker: 
```
#!/bin/bash


# Required volumes:
#   - `/var/lib/tftpboot` - This is where tftp data will go.
#   - `/pxemanager/data`  - data persistence (eg server and image data)
#
# A `config.local.php` file can be bind-mounted to `/pxemanager/config.local.php`
# if required.
#
# The `/var/lib/tftpboot` volume should be shared with a tftp server that
# actually serves the data. This will need to be pre-seeded manually with the
# required pxelinux.0, ldlinux.c32 and ipxe.lkrn files.


CD=$(dirname $(readlink -f $BASH_SOURCE))

#cd git && docker build . -t hradec/pxe-manager && cd ..
mkdir -p $CD/data $CD/tftp/pxelinux.cfg
docker rm --force pxe-manager && \
docker run --name pxe-manager  --restart=always  -d \
  --publish 8080:80 \
  --volume $CD/tftp:/var/lib/tftpboot \
  --volume $CD/data:/pxemanager/data \
  --volume $CD/log:/var/log \
  --volume $CD/php_errors.ini:/usr/local/etc/php/conf.d/errors.ini \
hradec/pxe-manager
```

As you can see, I'm trying to find error messages somewhere, but nothing shows up, apart from the normal access log in `docker logs pxe-manager`.

**Comment by ShaneMcC** [comment]
Hi,

The docker version is a bit less tested than not running in docker as I started using docker after writing this and haven't switched this over to docker in production yet.

I'll have a look at this over the weekend to see if I can reproduce.

**Comment by ShaneMcC** [comment]
Hi - This feels like a permissions issue.

The webserver runs as `www-data`, so the data directory and database need to be writable by that user.

I've pushed a change now for docker builds that should correct the permissions on startup (Can be disabled by setting `FIX_PERMISSIONS` env var to `false`) - Can you try again?
