### ISSUE TITLE
[Feature request] Add snippet support to images template

### ISSUE THREAD

**Issue by iMikeG6** [ShaneMcC/PXE-Manager#158]
Hello @ShaneMcC, thanks for this awesome project which i really like. I was used to Foreman but even though I really enjoy working with it, it's way to heavy for use just as a kickstart generator.

So I'm considering using pxe-manager, which is nice and pretty easy to use for simple uses cases, though, I think some improvements would benefit the community.

First, in Foreman template, you can create a template and in this template include snippet that are kind of templates that are only meant to be included in image template.

It'lld be really nice if you can implement something similar to what Foreman is doing with its template snippet. Below, here's an example:

```erb
<%#
Main post script, if it fails the last post is still executed.
%>
%post --log=/mnt/sysimage/root/install.post.log
logger "Starting anaconda <%= @host %> postinstall"
exec < /dev/tty3 > /dev/tty3
#changing to VT 3 so that we can see whats going on....
/usr/bin/chvt 3
<%= snippet_if_exists(template_name + " custom post") %>
<% if subnet.respond_to?(:dhcp_boot_mode?) || @host.subnet6.respond_to?(:dhcp_boot_mode?) -%>
<%= snippet 'Redhat - kickstart networking setup' %>
<% end -%>
```

In this example you have `<%= snippet 'Redhat - kickstart networking setup' %>` which is basically an include of the template name `Redhat - kickstart networking setup` for network configuration that can be used in others templates as well, without the need of recreating it on each template, which I think is great for keeping things clean.

What's your thoughts on that ?

**Comment by ShaneMcC** [comment]
There is already some support for this.

I support twig's `extends` and `use` (https://twig.symfony.com/doc/3.x/tags/use.html).

eg:

```twig
{% extends '19/kickstart' %}

{% block blah %}
# Something here
{% endblock %}
```

Will import the kickstart from image id 19, and then replace `block blah`

You can also use `use` or `include` in similar ways.

The template to use is the template id, then a `/`, then:

- `pxedata` for the pxedata section
- `script`, `kickstart` or `preseed` for the preseed/kickstart section
- `postinstall` for the post-install section

This will also automatically inherit any required variables from the referenced template(s)

This combined with templates not marked as available for use can probably provide for the use case you want, though maybe not quite as pretty if you're doing lots of them.
