### ISSUE TITLE
[Enhancement] ServerRoutes.php - allowInsecurePXEData - getEnable check condition for routes 

### ISSUE THREAD

**Issue by iMikeG6** [ShaneMcC/PXE-Manager#164]
Hi,

due to the use of iPXE and being the only bootp bin used in our environment, routes needed some adjustment.

In the iPXE embedded script I have set the following:

```
:net0
isset ${net0/mac} || goto no_nic
dhcp net0 || goto net1
chain http://${next-server}:80/pxe/pxedata/${net0/mac} || goto net1
```

So in order for the machine to boot whenever it is set to first boot on the Network card, I had to enable the pxe-manager option `allowInsecurePXEData`
However, when the machine is already provisioned and disabled in pxe-manager, the machine will always get the pxedata which will then be used to re-provision the machine. In order to avoid this infinite loop, I edit the php code to `src/routes/ServerRoutes.php` and added a new if condition ` $server->getEnabled() == true`

```php
if ($this->config['allowInsecurePXEData']) {
$router->get('/pxedata/([^/]+)', function($macaddr) use ($router, $displayEngine, $api) {
	$server = $api->getServerFromMAC($macaddr);
	if (!($server instanceof Server)) { return $this->showUnknown($displayEngine); }

	$image = $server->getBootableImage();
	if ($image instanceof BootableImage && $server->getEnabled() == true) {
		$api->createServerLog($serverid, 'SYSTEM', 'insecure pxedata accessed by ' . getUserInfoString());
		die($server->getDisplayEngine()->render($image->getID() . '/pxedata'));
	} else {
		die();
	}
});
}
```

I also added this trick to other routes so data could only be retrieved when the machine is enabled for provisioning. Which is, IMO a bit more secure in the end.

Hope it helps

**Comment by ShaneMcC** [comment]
I've added a `allowInsecurePXEDataWhenEnabled` flag now that will result in similar behaviour.
