### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by akashtalole** [ShaneMcC/PXE-Manager#24]
PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/pxe-manager/functions.php:15\nStack trace:\n#0 /var/www/pxe-manager/functions.php(15): PDO->__construct('sqlite:/var/www...')\n#1 /var/www/pxe-manager/public/index.php(2): require_once('/var/www/pxe-ma...')\n#2 {main}\n  thrown in /var/www/pxe-manager/functions.php on line 15

**Comment by ShaneMcC** [comment]
Hi,

Seems like you're missing the pdo sqlite driver.

Can you provide some more information about your setup?
Did you follow the guide at https://github.com/ShaneMcC/PXE-Manager/wiki/Install-Guide or not? If not you'll want to make sure you install the appropriate package that includes the driver, eg `php-sqlite3`, `php7.1-sqlite3`, `php7.2-sqlite3` or `php7.3-sqlite3` etc (These are the ubuntu package names, debian or centos are similar I believe)

**Comment by akashtalole** [comment]
I have setup on Ubuntu 16.04 using https://github.com/ShaneMcC/PXE-Manager/wiki/Install-Guide.
pdo sqlite driver is installed and enabled.

**Comment by akashtalole** [comment]
Confusion in config.php and config.local.php
```php
<?php
        // Database Details
        // only sqlite is supported at the moment.
        $database['type'] = getEnvOrDefault('DB_SERVER_TYPE', 'sqlite');

        // Used only if type is sqlite.
        $database['file'] = getEnvOrDefault('DB_FILE', __DIR__ . '/data/db.sqlite');
```

**Comment by ShaneMcC** [comment]
Hi,

As before, that error suggests that the pdo sqlite driver isn't installed, or isn't being loaded by php, so you'll need to fix that - there's not much I can do to help as it's not really an issue with PXE-Manager itself.

If you've followed the guide you should see something like this when you run `dpkg -l | grep php.*sqlite3`:

```
root@deploy:~# dpkg -l | grep php.*sqlite
ii  php7.0-sqlite3                      7.0.31-1+ubuntu16.04.1+deb.sury.org+1      amd64        SQLite3 module for PHP
ii  php7.1-sqlite3                      7.1.20-1+ubuntu16.04.1+deb.sury.org+1      amd64        SQLite3 module for PHP
root@deploy:~#
```

And `php -c /etc/php/7.1/apache2 -m | grep -iE "(pdo|sql)"` should show `pdo_sqlite` and `sqlite3`:
```
root@deploy:~# php -c /etc/php/7.1/apache2 -m | grep -iE "(pdo|sql)"
PDO
pdo_sqlite
sqlite3
root@deploy:~#
```

Can you confirm that you have restarted the apache webserver (`service apache2 restart`) after installing the packages (Assuming PHP is running as a module as per the guide)?


I'm not sure which bit of the `config.php` or `config.local.php` you're confused at, you shouldn't need to change it for the most part for the default install.

**Comment by akashtalole** [comment]
I have restarted apache. still same errror. 
```
akash@akash:~$ dpkg -l | grep php.*sqlite3
ii  php7.1-sqlite3                              7.1.20-1+ubuntu16.04.1+deb.sury.org+1        amd64        SQLite3 module for PHP
```

```
akash@akash:~$ php -c /etc/php/7.1/apache2 -m | grep -iE "(pdo|sql)"
PDO
pdo_sqlite
sqlite3
```

**Comment by ShaneMcC** [comment]
I'm afraid I don't have much more suggestions to add, you'll need to look at the server configuration and make sure that you are using the right version of PHP and that module is being loaded.

It may be that existing configuration you have isn't loading the module (or that your webserver is using the wrong version of PHP compared to the module that was installed.) - The guide is designed to be used on a fresh new install.

If you create a `phpinfo.php` file in the web-root:
```
echo "<?php phpinfo();" > /var/www/pxe-manager/public/phpinfo.php
```
And add:
```
RewriteRule ^phpinfo.php$ - [L]
```
to `/var/www/pxe-manager/public/.htaccess` above the `# Everything Else` line you should then be able to visit a page at `http://yourserver/phpinfo.php` that will display information about how PHP is running within your webserver.

Key things to look for:
- The PHP version at the top of the page (eg "PHP Version 7.1.20-1+ubuntu16.04.1+deb.sury.org+1")
- "Additional .ini files parsed" should include somewhere something like `/etc/php/7.1/apache2/conf.d/10-pdo.ini` and `/etc/php/7.1/apache2/conf.d/20-pdo_sqlite.ini`
- There should be a "PDO" and "pdo_sqlite" section on the page.

**Comment by akashtalole** [comment]
PHP7.0 was enabled therefore this errors was occurring. I enabled PHP7.1. Issue is resolved. Thanks @ShaneMcC

**Comment by ShaneMcC** [comment]
Fantastic news, happy to help :)

I'll close this off now then, feel free to raise any other issues you encounter.
