### ISSUE TITLE
setup failes at composer install step

### ISSUE THREAD

**Issue by reinethernal** [ShaneMcC/PXE-Manager#67]
root@netboot:/var/www/pxe-manager# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file

  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by ShaneMcC** [comment]
This error looks like your version of composer is old but php is new (https://github.com/composer/composer/issues/7783) - can you confirm what version of each you are using?

**Comment by reinethernal** [comment]
PHP Version 7.1.33-1+ubuntu16.04.1+deb.sury.org+1

Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34

**Comment by reinethernal** [comment]
After composer upgrede installation succeeded. Thank you!
