### ISSUE TITLE
Can't view images when using PHP 7.4+

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/PXE-Manager#87]
[This cool bug](https://github.com/bramus/router/issues/113) means that the image routes with (.json)? at the end don't get their arguments parsed properly.

You could probably work around it by defining separate JSON routes, but it might be worth just documenting that it needs PHP <7.4 and updating the Dockerfile accordingly?

**Comment by greboid** [comment]
Its not just the image routes, its any of the routes that have the api on it, so most of them
